language: python

python:
  - '2.7'
  - '3.4'

env:
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9

install:
  - 'pip install -q Django==$DJANGO_VERSION'
  - 'pip install argparse pep8'
  - 'pip install .'

script:
  - 'python runtests.py --no-coverage'
